import "./globals.css";
import { Roboto } from "next/font/google";
import style from "./page.module.css";
import { TheHeader } from "@/components/Header/Header";
import { TheFooter } from "@/components/Footer/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${style.mainBox} ${roboto.className}`}>
        <TheHeader></TheHeader>

        <main className={style.contentBox}>{children}</main>

        <TheFooter></TheFooter>
      </body>
    </html>
  );
}
